trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  connectedServiceDir: '$(Build.SourcesDirectory)\ODataConnectedService'
  sln: '$(connectedServiceDir)\ODataConnectedService.sln'
  testSln: '$(connectedServiceDir)\ODataConnectedService.Tests.sln'

steps:
- task: NuGetToolInstaller@0
  inputs:
    versionSpec: '>=5.2.0'

- task: NuGetCommand@2
  displayName: 'Nuget restore - ODataConnectedService.sln'
  inputs:
    restoreSolution: '$(sln)'

- task: VSBuild@1
  displayName: 'Build solution - ODataConnectedService.sln'
  inputs:
    solution: '$(sln)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: 'Nuget restore tests - ODataConnectedServiceTests.sln'
  inputs:
    restoreSolution: '$(testSln)'

- task: VSBuild@1
  displayName: 'Build tests solution - ODataConnectedServiceTests.sln'
  inputs:
    solution: '$(testSln)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '$(connectedServiceDir)\test\ODataConnectedService.Tests\bin\$(BuildConfiguration)\ODataConnectedService.Tests.dll'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    searchFolder:  '$(System.DefaultWorkingDirectory)'

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: "ESRP CodeSigning - OData"
    FolderPath: '$(connectedServiceDir)\src\bin\$(BuildConfiguration)\Release'
    Pattern: '*.dll,*.exe'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "keyCode": "MSSharedLibSnKey",
          "operationSetCode": "StrongNameSign",
          "parameters": null,
          "toolName": "sn.exe",
          "toolVersion": "V4.6.1586.0"
        },
        {
          "keyCode": "MSSharedLibSnKey",
          "operationSetCode": "StrongNameVerify",
          "parameters": null,
          "toolName": "sn.exe",
          "toolVersion": "V4.6.1586.0"
        },
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolSign",
          "parameters": [
          {
            "parameterName": "OpusName",
            "parameterValue": "TestSign"
          },
          {
            "parameterName": "OpusInfo",
            "parameterValue": "http://test"
          },
          {
            "parameterName": "PageHash",
            "parameterValue": "/NPH"
          },
          {
            "parameterName": "TimeStamp",
            "parameterValue": "/t \"http://ts4096.gtm.microsoft.com/TSS/AuthenticodeTS\""
          }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        },
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolSign",
          "parameters": [
          {
            "parameterName": "OpusName",
            "parameterValue": "TestSign"
          },
          {
            "parameterName": "OpusInfo",
            "parameterValue": "http://test"
          },
          {
            "parameterName": "Append",
            "parameterValue": "/AS"
          },
          {
            "parameterName": "PageHash",
            "parameterValue": "/NPH"
          },
          {
            "parameterName": "FileDigest",
            "parameterValue": "/fd sha256"
          },
          {
            "parameterName": "TimeStamp",
            "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
          }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        },
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolVerify",
          "parameters": [
          {
            "parameterName": "VerifyAll",
            "parameterValue": "/all"
          }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
